### ISSUE TITLE
[BUG]: Discord to QQ 转发发生错误

### ISSUE THREAD

**Issue by ZoruaFox** [Cola-Ace/koishi-plugin-bridge-discord-qq#3]
在 Discord 消息发往 QQ 时发现无法发送至对应群，QQ 发往 Discord 未见明显异常。

开启 debug 后可观察到以下报错：

```shell
Error: Error with request send_group_msg, args: {"group_id":993956989,"message":[{"type":"image","data":{"file":"[https://cdn.discordapp.com/avatars/922121068582404118/ccba1ff14d91736dec74ae231b6fc896.png?size=64","cache":0}},{"type":"text","data":{"text":"[Discord]](vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) Zorua Fox:\n132"}}]}, retcode: 1200 
at _Internal._get (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:119:11) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
at async _Internal.<computed> [as sendGroupMsg] (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:162:20) 
at async OneBotMessageEncoder.flush (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:763:330) 
at async OneBotMessageEncoder.send (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules@satorijs\core\lib\index.cjs:620:5) 
at async Proxy.sendMessage (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules@satorijs\core\lib\index.cjs:355:22) 
at async Proxy.<anonymous> (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-bridge-qq-discord\lib\index.js:690:38)
```

**Comment by Cola-Ace** [comment]
可能和koishi或者qqbot所在的服务器能否访问discord有关，我为了保险起见把qqbot和koishi都放在非大陆服务器上的

ZoruaFox ***@***.***> 于 2024年11月3日周日 下午5:41写道：

**Comment by ZoruaFox** [comment]
> 可能和koishi或者qqbot所在的服务器能否访问discord有关，我为了保险起见把qqbot和koishi都放在非大陆服务器上的

我的koishi和qqbot在同一个服务器，不知道为什么出现同一个环境下两个平台互通行为不同的情况

**Comment by Cola-Ace** [comment]
我推测你是koishi配置了proxy，但是qqbot没有配置
虽然是koishi上显示的报错，但是实际上是qqbot访问不到 `cdn.discordapp.com` 导致的报错（即koishi告诉qqbot要发送的内容，qqbot获取消息内容中的图片插入到文本中）
这种情况你可能需要给qqbot也配置代理，或者使用非大陆服务器
如果你有linux的非大陆服务器的话可以考虑部署napcat或其他支持onebot协议的headless客户端

**Comment by ZoruaFox** [comment]
> 我推测你是koishi配置了proxy，但是qqbot没有配置 虽然是koishi上显示的报错，但是实际上是qqbot访问不到 `cdn.discordapp.com` 导致的报错（即koishi告诉qqbot要发送的内容，qqbot获取消息内容中的图片插入到文本中，但是qqbot无法访问discord，导致报错） 这种情况你可能需要给qqbot也配置代理，或者使用非大陆服务器 如果你有linux的非大陆服务器的话可以考虑部署napcat或其他支持onebot协议的headless客户端

确实是 NapCat 侧的报错：
```shell
2024-11-05 11:07:41 [ERROR] bot(xxxx) | 发生错误 ConnectTimeoutError: Connect Timeout Error
    at onConnectTimeout (node:internal/deps/undici/undici:6635:28)
    at node:internal/deps/undici/undici:6587:50
    at Immediate._onImmediate (node:internal/deps/undici/undici:6617:37)
    at process.processImmediate (node:internal/timers:478:21) 
```
```shell
2024-11-05 11:01:10 [ERROR] bot(xxxx) | 发生错误 Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (node:_tls_wrap:1727:19)
    at TLSSocket.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) 
```
以上报错理论上同属连接问题，我使用的是 Clash 代理的方式，由于 NapCat 没有明确提到配置代理的办法（至少文档未提及），我在使用 TUN 模式代理全局流量后依然显示以上报错（非大陆机器买不起了）。

正在考虑要不要在 NapCat 侧开一个请求支持配置 Proxy 的 Issue…

**Comment by Cola-Ace** [comment]
> > 我推测你是koishi配置了proxy，但是qqbot没有配置 虽然是koishi上显示的报错，但是实际上是qqbot访问不到 `cdn.discordapp.com` 导致的报错（即koishi告诉qqbot要发送的内容，qqbot获取消息内容中的图片插入到文本中，但是qqbot无法访问discord，导致报错） 这种情况你可能需要给qqbot也配置代理，或者使用非大陆服务器 如果你有linux的非大陆服务器的话可以考虑部署napcat或其他支持onebot协议的headless客户端
> 
> 确实是 NapCat 侧的报错：
> ```shell
> 2024-11-05 11:07:41 [ERROR] bot(xxxx) | 发生错误 ConnectTimeoutError: Connect Timeout Error
>     at onConnectTimeout (node:internal/deps/undici/undici:6635:28)
>     at node:internal/deps/undici/undici:6587:50
>     at Immediate._onImmediate (node:internal/deps/undici/undici:6617:37)
>     at process.processImmediate (node:internal/timers:478:21) 
> ```
> ```shell
> 2024-11-05 11:01:10 [ERROR] bot(xxxx) | 发生错误 Error: Client network socket disconnected before secure TLS connection was established
>     at TLSSocket.onConnectEnd (node:_tls_wrap:1727:19)
>     at TLSSocket.emit (node:events:531:35)
>     at endReadableNT (node:internal/streams/readable:1696:12)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) 
> ```
> 以上报错理论上同属连接问题，我使用的是 Clash 代理的方式，由于 NapCat 没有明确提到配置代理的办法（至少文档未提及），我在使用 TUN 模式代理全局流量后依然显示以上报错（非大陆机器买不起了）。
> 
> 正在考虑要不要在 NapCat 侧开一个请求支持配置 Proxy 的 Issue…

你可以看一下类似的基于 QQNT 开发的机器人支不支持配置 proxy，如果 QQNT 方面没做配置 proxy 的话大概率这些机器人都是不支持配置 proxy 的
理论上可以在 koishi 上获取图片内容后再传给 qqbot，但是在实际应用中可能会因为图片文件太大或者有多个图片导致消息发送失败，这点我晚些时候会研究一下

**Comment by Cola-Ace** [comment]
经尝试后仍不可行，网络环境问题非本插件问题，此 issue 将被关闭

**Comment by ZoruaFox** [comment]
多日之后的补充：

bridge-discord-qq 的 Discord 转 QQ 发送图片方法失败之后我又看了一些相似原理的项目，发现大多数项目均是采用了“ **Koishi 告诉 QQBot 要发送的内容，QQBot 获取消息内容中的图片插入到文本中**”的发送方法，这种方法需要目标机器的 QQBot 处在海外网络环境时才能够正确访问 *.discord.com 。但是根据多次个人实验结果发现，即使开启了像 Clash TUN 这种代理全局应用流量的模式下，QQBot 均无法获取来自 *.discord.com 的图片，在现有的实现方式下，只能通过将机器架设在海外解决该问题。

但在我长期运行的另一个机器人实例 [Akari Bot](https://github.com/Teahouse-Studios/akari-bot) 下，所有关于图片的消息均能被正常发送，和核心开发者讨论发现 Akari Bot 使用的是先获取图片再发送 base64 的方式发送的（即“**理论上可以在 Koishi 上获取图片内容后再传给 QQBot**”），这种方式自从使用过后并未出现明显问题（甚至对于获取 Wikipedia 上的大图片），但是 Akari Bot 的相关方法（SDK）经过魔改，或许需要进一步研究。

写这个讨论记录一下另一种可能实现的方法，这个 issue 可能会被其他同类项目引用。

**Comment by Cola-Ace** [comment]
该问题已在 v1.8.0 解决
https://github.com/Cola-Ace/koishi-plugin-bridge-discord-qq/commit/49145b70f965ac878156f43260bf78f1d027f9c6
